INSERT INTO LIBRARY VALUES (101, 'A, B, C, D', 'CoffeShop');
INSERT INTO LIBRARY VALUES (102, 'A, B, C, D', 'BookShop');
INSERT INTO LIBRARY VALUES (103, '', 'Animal Library');
INSERT INTO LIBRARY VALUES (104, '', 'IT Library');

INSERT INTO LIBRARY VALUES (105, 'A, B, C, D', 'New Library');
INSERT INTO LIBRARY VALUES (106, 'A, B, C, D', 'Old Library');
INSERT INTO LIBRARY VALUES (107, 'bbb1, cc2, dd3', 'A');
INSERT INTO LIBRARY VALUES (108, 'zz9, yy8', 'Z Library');
